spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: admin
    url: jdbc:h2:mem:admin_service_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
#  jpa:
#    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
