version: '3.7'

services:
  mysql:
    container_name: admin-service-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=services
    security_opt:
      - seccomp:unconfined
    ports:
      - 3307:3306
    networks:
      - jobee_network

  rabbitmq:
    container_name: adm_review_rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=91728e06-2d63-4a3d-b3a7-bd5a8ecf8a58
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - jobee_network

networks:
  jobee_network:

