name: CI Pipeline

on:
  push:
    branches:
      - 'bugfix/**'
      - 'refactor/**'
      - 'feat/**'
  # Habilita o gatilho manual da interface do github actions
  workflow_dispatch:

jobs:
  tests:
    name: Tests Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo fonte
        uses: actions/checkout@v3

      - name: Setup JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Permitir execução do gradlew
        run: chmod +x ./gradlew

      - name: Run application tests
        run: ./gradlew test


